### PR TITLE
Plot truncated pexecs (R version) 

### PR DESCRIPTION
**Pull request by snim2**
This is a version of #423 which uses an R library to compute confidence intervals, rather than the Python statsmodels library.

Latest result: [multinomial_R.pdf](https://github.com/softdevteam/warmup_experiment/files/1182775/multinomial_R.pdf)

The R library has been added to `build_stats.sh` (in a separate commit).

### CODE REVIEW

**Comment by ltratt** [comment]
The `os.environ` stuff is a bit evil, but if it works it works. Do you want to squash?

**Comment by snim2** [comment]
Yes, it's what we do in the other scripts. Do you want to leave commit e279887 in or out?

**Comment by ltratt** [comment]
You mean as a separate non-squashed commit? I don't mind either way.

**Comment by snim2** [comment]
No, I mean do we really need it? Without it users will need to do some R magic to make this script work, but I'm not sure we are really expecting other users to run this one?

**Comment by ltratt** [comment]
Ah, I see. I think this script is useful: just because our *current* data shows this pattern doesn't mean others' data will. Other people might also want to work out if they can get away with less pexecs in their case. So I think we should keep it in.

**Comment by snim2** [comment]
OK, splat.

**Review by ltratt — APPROVED** [review]

**Pull request merged**
