### PR TITLE
Check SSH connection ahead of time.

### PR DESCRIPTION
**Pull request by vext01**
I wanted to allow the stop cookie command to fail, but sadly that won't work due to the way we use the return value to notice the existence of the file :( oh well.

OK?

### CODE REVIEW

**Comment by vext01** [comment]
Tested this with the id_rsa file absent. It crashes as expected :)

**Comment by snim2** [comment]
OK, have you tested this somehow?

**Comment by snim2** [comment]
OK, this looks good to me, are you happy for me to merge as-is?

**Comment by vext01** [comment]
Sure!

**Review by snim2 — APPROVED** [review]

**Pull request merged**
