### PR TITLE
Use batch mode for SSH.

### PR DESCRIPTION
**Pull request by vext01**
Prevents krun hanging on a password prompt if the id_rsa file is missing.

Will require a branch sync soon.

OK?

### CODE REVIEW

**Comment by ltratt** [comment]
Branch sync?

**Comment by vext01** [comment]
Another PR is about to go in, so this will be out of sync...

**Review by ltratt — APPROVED** [review]

**Comment by ltratt** [comment]
Ah, no, you only need a sync if you have conflicts. This one is fine as-is.

**Comment by vext01** [comment]
OK, go ahead.

**Pull request merged**
