### PR TITLE
Changepoints are blobs at ymin.

### PR DESCRIPTION
**Pull request by snim2**
First bash at blobby changepoints:

blobby

I'm not sure what you want to do about the segment means.

### CODE REVIEW

**Comment by ltratt** [comment]
I think this is good. For the paper, I think we might need to simply remove the means, because they're probably going to be invisible. Or, maybe, we show them in a case where they're much clearer (i.e. when the data occupies a much greater portion of the y axis).

**Comment by snim2** [comment]
So, are we saying we want different representations of changepoints for the paper and for our own use?

**Comment by ltratt** [comment]
Probably (I can't say _for sure_, but I think so).

**Comment by snim2** [comment]
OK, with this commit `--with-changepoint-means` produces this:

cpt_means

`--with-changepoints` produces this:

cpts

**Comment by ltratt** [comment]
Excellent!

**Comment by snim2** [comment]
OK, let's wait for @vext01 to review.

**Review by ltratt — APPROVED** [review]

**Comment by ltratt** [comment]
I think it's fine for this to go in now -- we'll prboably need to do more fiddling in the future, but this is plenty good enough for now.

**Comment by snim2** [comment]
OK, sure

**Pull request merged**
