### PR TITLE
Recursively clone Krun.

### PR DESCRIPTION
**Pull request by vext01**
OK?

### CODE REVIEW

**Comment by snim2** [comment]
Is there any chance that someone might run `./build.sh` in an old clone of this repo? (i.e. should we say `git submodule update --init --recursive`)

**Comment by ltratt** [comment]
No, they should be wiping old repos and rerunning. [Until last week, `make clean` didn't work properly.]

**Comment by vext01** [comment]
The clone is guarded like this:

```
     if ! [ -d "${HERE}/krun" ]; then
```

For the final version we will clone a tag, so it won't matter. Right?

**Comment by snim2** [comment]
OK, sounds good to me.

**Review by snim2 — APPROVED** [review]

**Pull request merged**
