### PR TITLE
Pad Y range by 2%.

### PR DESCRIPTION
**Pull request by vext01**
Avoids points touching the top and bottom of graph.

### CODE REVIEW

**Comment by ltratt** [comment]
Can you show the effects of this? Note that you can upload images to github!

**Comment by vext01** [comment]
Yes! But your'e not supposed to have seen this yet. I'm trying to upload a pic!

**Comment by vext01** [comment]
[silly.pdf](https://github.com/softdevteam/warmup_experiment/files/8652/silly.pdf)

**Comment by ltratt** [comment]
OK, I'm not sure I see what the effect is. Maybe a before/after?

**Comment by vext01** [comment]
[after.pdf](https://github.com/softdevteam/warmup_experiment/files/8656/after.pdf)

Before, the outlier splits the graph in two. I thought it was two graphs for a moment.

**Comment by ltratt** [comment]
Ah, yes, I agree the `after.pdf` file is much better.

**Pull request merged**
