### PR TITLE
Build simplifications

### PR DESCRIPTION
**Pull request by ltratt**
[Needs #188 to be merged first.]

A couple of simple tweaks to `build.sh` -- the commit messages explain this in better detail.

### CODE REVIEW

**Comment by vext01** [comment]
These are fine.

**Comment by ltratt** [comment]
Wait a sec while I rebase this one.

**Review by vext01 — APPROVED** [review]

**Comment by ltratt** [comment]
OK, should be ready for merging.

**Comment by vext01** [comment]
ready?

**Pull request merged**
