### PR TITLE
Disable luindex (and other related things)

### PR DESCRIPTION
**Pull request by ltratt**
*Needs testing before merging*

This is three things in one, so it's best to read the individual commits.

This needs at least light testing before merging. Edd, can you look into that please? I'd suggest reducing `ITERATIONS` to (say) 10 and `PROCESSES` to (say) 3, which shouldn't take *too* long to execute.

### CODE REVIEW

**Review by vext01 — APPROVED** [review]
I've run 3 reps of 3x10 experiments and no issues.

**Comment by vext01** [comment]
go ahead and squash

**Comment by ltratt** [comment]
OK, see if that squashing works for you.

**Comment by vext01** [comment]
Ah, one more detail, which i need to test actually, I think you need:

```diff
                     stdout, stderr, rc = run_shell_cmd_bench(
                         "%s -jar %s %s -n %s" % (jvm_cmd, JAR, benchmark,
-                                                 ITERATIONS + 1), platform)
+                                                 ITERATIONS + 1), platform, failure_fatal=False)
```

or `run_shell_cmd_bench` is gong to stop the runner.

**Comment by ltratt** [comment]
Shall I do that and squash at the same time or ...?

**Comment by vext01** [comment]
Let me check it. One moment.

**Comment by vext01** [comment]
I can test this by killing one thread of the vm during a run.

Before:

```
  File "/home/kruninit/warmup_experiment/krun/krun/util.py", line 52, in fatal
    raise FatalKrunError(msg)
krun.util.FatalKrunError: Command failed: '/home/kruninit/warmup_experiment/work/mx/mx --java-home=/home/kruninit/warmup_experiment/work/graal-jvmci-8/jdk1.8.0/product -p /home/kruninit/warmup_experiment/work/graal/ vm -XX:+UseJVMCICompiler -jar extbench/dacapo-9.12-bach.jar avrora -n 11'
stdout:

stderr:
===== DaCapo 9.12 avrora starting warmup 1 =====
===== DaCapo 9.12 avrora completed warmup 1 in 3078344857 nsec =====
...
```

After:
```
graal:
  avrora: 0
===== DaCapo 9.12 avrora starting warmup 1 =====
===== DaCapo 9.12 avrora completed warmup 1 in 3047048276 nsec =====
===== DaCapo 9.12 avrora starting warmup 2 =====
===== DaCapo 9.12 avrora completed warmup 2 in 2060842600 nsec =====
===== DaCapo 9.12 avrora starting warmup 3 =====
===== DaCapo 9.12 avrora completed warmup 3 in 1953213189 nsec =====
===== DaCapo 9.12 avrora starting warmup 4 =====
===== DaCapo 9.12 avrora completed warmup 4 in 1932656164 nsec =====
===== DaCapo 9.12 avrora starting warmup 5 =====
===== DaCapo 9.12 avrora completed warmup 5 in 1920809910 nsec =====
===== DaCapo 9.12 avrora starting warmup 6 =====

 1 2
```

Can you add some kind of a message that indicates that the pexec failed. Otherwise I think that has worked OK.

In the latter case, you will get a results file like:
```
processnum,benchmark,0,1,2,3,4,5,6,7,8,9
1,avrora,3.07552784,2.068373501,1.941320083,1.936208724,1.93754041,1.930098086,1.913583866,1.93886327,1.909749109,1.924084161
2,avrora,3.081634177,2.061214975,1.923640755,1.945695335,1.927211131,1.930267844,1.931112786,1.923637596,1.902661694,1.89429299
```

i.e. with a missing line. You OK with that? I think perhaps we might need to insert some kind of a crash marker, or adjust the consumers so-as they don't blindly assume the lines are consecutive pexecs. If you see what I mean?

**Comment by ltratt** [comment]
The pexec numbers will be non-consecutive. I don't think we can do anything else TBH.

**Comment by vext01** [comment]
From a quick look at the conversion code, it looks like the pexec number is ignored, and all pexecs are assumed to be consecutive:
https://github.com/softdevteam/warmup_experiment/blob/master/warmup/krun_results.py#L35

So if we have pexecs `[1,3,7,9]` in our CSV, we would have pexecs `[0,1,2,3]` once converted. IIRC, the convention used in krun for a crashed pexec is the empty list, but let me check.

**Comment by ltratt** [comment]
Wouldn't the important code be the `csv_to_krun` code in this case?

**Comment by vext01** [comment]
It imports and uses the code i linked above:
https://github.com/softdevteam/warmup_experiment/blob/master/bin/csv_to_krun_json#L17

**Comment by ltratt** [comment]
OK. I'm going to have to leave this part of things to you. Should it be a separate PR?

**Comment by snim2** [comment]
Probably sensible to just raise an issue on this, is there a test case yet?

**Comment by vext01** [comment]
We can do a separate PR yeah. Sarah and I can handle the crashing case.

I'm worried that having the wrong number of elements in the results file will confuse other parts of our code, so I'd like to look into it quickly.

**Comment by vext01** [comment]
Ready for me to merge this then?

**Comment by ltratt** [comment]
I still need to add `failure_fatal=False` I assume?

**Comment by vext01** [comment]
Ah yeah, OK.

**Comment by ltratt** [comment]
OK, force pushed with that update.

**Pull request merged**
