### PR TITLE
Slowdown must always check for a steady state.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by ltratt** [comment]
How difficult would it to be to hoist the "no steady state" check to the beginning of the `if` block so that each branch doesn't have to check it?

**Comment by snim2** [comment]
Please check that this is equivalent to what we had before...

**Comment by ltratt** [comment]
It looks good to me, but we should double-check it on the plots to be doubly sure.

**Comment by snim2** [comment]
OK, replotting b3 now

**Comment by snim2** [comment]
Test case: [bencher3_warmup_07_plots.pdf](https://github.com/softdevteam/warmup_experiment/files/592015/bencher3_warmup_07_plots.pdf)

**Comment by ltratt** [comment]
This looks good to me. Squash and I'll merge?

**Comment by snim2** [comment]
Squashed

**Review by ltratt — APPROVED** [review]

**Pull request merged**
