### PR TITLE
Put "Print-tracing" Versions of Benchmarks into Master Branch

### PR DESCRIPTION
**Pull request by vext01**
This PR moves all of the tracing versions of benchmarks into the master branch and updates the documentation making users aware of their existence. While I was in `README.md` I also linked to the paper and said roughly how to run the experiment.

@cfbolz Can you let me know if the file (in your branch) `benchmarks/binarytrees/ruby/trace_debug_bench.rb` should be included. I think it should not be included as we already have `benchmarks/binarytrees/ruby/trace_bench.rb`, right?

OK?

Thanks

### CODE REVIEW

**Comment by cfbolz** [comment]
I agree that the file can go. if we add more benchmarks it might be useful again (maybe), but in that case we can fish it from history.

**Comment by vext01** [comment]
OK, so if all looks in check, go ahead and merge.

**Comment by ltratt** [comment]
Is there a reason why this wasn't merged?

**Comment by ltratt** [comment]
[I just quickly did the rebase -- though I haven't pushed! -- and there's a single, rather trivial, conflict to fix. So I think we should rebase then merge.]

**Pull request merged**
