### PR TITLE
Remove suptitle.

### PR DESCRIPTION
**Pull request by vext01**
Remove the suptitle. It overlaps the graph headers and says nothing that isn't already said in the individual graph headers.

OK?

### CODE REVIEW

**Comment by snim2** [comment]
I agree that removing the suptitle is a good idea.

At some point today I need to push the changes which add percentage outliers to the charts, separately label the unique and common outliers, and draw in the mean and 5-sigma. 

Do you want to merge this now, then have me pull that into the new changes and merge it in, or should we close this PR now and I'll add this to the upcoming PR?

**Comment by vext01** [comment]
Whatever is easiest for you really. Please make sure that all the statistical stuff can be switch off at the command line, as the draft won't include any statistics.

Thanks

**Comment by snim2** [comment]
It already can, don't worry.

**Comment by vext01** [comment]
So up to you if you want to merge this now.

**Comment by snim2** [comment]
I've added this to my other branch and will push in a minute...

**Comment by vext01** [comment]
ok, thanks

**Pull request closed without merging**
