### PR TITLE
Create summary tables from startup results.

### LINKED ISSUE #200: New script to generate useful information from the results of the startup experiment
We need to generate useful output from the results of the startup experiments. Our usual plots are not very useful, tables with means and confidence intervals would be more useful.

### PR DESCRIPTION
**Pull request by snim2**
This is a first bash at producing tables from the startup experiment. The result is a LaTeX file with averages of startup times listed per-vm and per-language variant.

I'm not sure whether that is really the most useful presentation of the data, so suggestions are welcome.

A short test from bencher2 can be found here: [table.pdf](https://github.com/softdevteam/warmup_experiment/files/564517/table.pdf)

Fixes #200

### CODE REVIEW

**Comment by vext01** [comment]
Here's some thoughts.
- We need confidence intervals. You can use the bootstrap method from libkalibera. I'll look for examples for you soon.
- Remove `default-` from language variants. Readers wont care for that.
- That column should be just `Language` too.
- Shorten `Average startup time (seconds)` to `Mean startup (s)`
- I wonder if the second table is useful... for `default-java` you will be munging hotspot and Graall into one. Perhaps leave the table, and we can choose to use it, or not, later.
- Can we make a table keyed by benchmark and VM?

**Comment by vext01** [comment]
Example of bootstrapping confidence intervals from pyhyp paper:
https://github.com/softdevteam/pyhyp_experiments/blob/master/latex_table.py#L200

**Comment by vext01** [comment]
I wonder if the second table needs geomeans. The benchmark pair table will.

You should find geomean code in that same file.

**Comment by snim2** [comment]
Is it useful to have a table keyed by benchmark, when we don't actually run the benchmarks? I did think about this then removed it, perhaps erroneously.

**Comment by vext01** [comment]
Hah, you are completely right. My bad!

**Comment by vext01** [comment]
but we do still need CIs.

**Comment by snim2** [comment]
Will do that next

**Comment by ltratt** [comment]
This is a good first start!

I think the first table should be "VM | Time(s)" (shorter column headings will be vital given the layout we have to hit) and we explain in the caption that it's the mean (with 99% confidence intervals). I don't think we want the second table at all?

Some LaTeX nerdery: we use `booktabs` and its `toprule`/`midrule`/`bottomrule` stuff (and no vertical lines). The docs for it are annoyingly opinionated to the extent that they can be off-putting, but it's hard to disagree with the beautiful output it leads to.

I am a bit surprised by the HHVM numbers, though without any concrete reason for being so. Can someone maybe double check that we've measured the right thing?

**Comment by snim2** [comment]
I have changed the column names. The CI stuff isn't ready to push yet. I have used `booktabs` from the start, does this need changing?

(BTW the data was from a very short run on Bencher2)

**Comment by ltratt** [comment]
Ah, yes, I can see the booktabs thing now. Mea culpa! We just need to get rid of the ugly vetical bar in the table (i.e. should be `{lr}` not {l|r}). I'm not sure what "CI stuff" is?

**Comment by snim2** [comment]
CI == "confidence interval"!

**Comment by ltratt** [comment]
Aha!

**Comment by snim2** [comment]
Next test case: [table.pdf](https://github.com/softdevteam/warmup_experiment/files/566930/table.pdf)

Confidence intervals are in, so this is now ready for another review. We need to merge this before #218 which contains some similar code factored out into a library module.

**Comment by vext01** [comment]
Minor nits/thoughts.
- set the error in smaller font
- centre column headings?
- how many DPs do we want on error?

**Comment by vext01** [comment]
FWIW, in the pyhyp paper, we used 3DP for measurements, and 4DP for error.

You will need more DP due to the nature of what we are measuring. How about 5/6?

**Comment by ltratt** [comment]
I'm not quite sure why the VM heading is to the left of the VM names below?

**Comment by snim2** [comment]
Test case again: [table.pdf](https://github.com/softdevteam/warmup_experiment/files/567014/table.pdf)

**Comment by ltratt** [comment]
Works for me. If Edd is happy, then I think we can squash, then merge.

**Comment by vext01** [comment]
Teensy nit. \pm should be small too, right?

**Comment by vext01** [comment]
Other than that, nice!

**Comment by vext01** [comment]
squash?

**Comment by vext01** [comment]
done?

**Comment by snim2** [comment]
Yup!

**Review by vext01 — APPROVED** [review]

**Pull request merged**
