### PR TITLE
Use LaTeX machine names.

### LINKED ISSUE #245: Machine names need to be formatted as in the paper
Currently plots are in the "old" format (e.g. "Linux1/i7-4790K"). They should be converted to the new (e.g. "Linux$_\textrm{4790K}$").

### PR DESCRIPTION
**Pull request by snim2**
Fixes #245

Example:

[test_machine_name.pdf](https://github.com/softdevteam/warmup_experiment/files/587969/test_machine_name.pdf)

### CODE REVIEW

**Comment by ltratt** [comment]
Is it just me, or is the subscript the same size as the main text?

**Comment by snim2** [comment]
It's in `textrm` right? So I think that's what we'd expect

**Comment by ltratt** [comment]
The subscript should be in a smaller font (normally). I thought I was going mad, but I've checked and you can see the issue here:
image
The transparent text in the background is the paper, the black text in the foreground the PDF on this PR. Notice that the "Linux" text is exactly the same size in both PDFs, but the transparent subscript text is much smaller.

I wonder if matplotlib does a sort of latex simulation or something and gets the sizes wrong? It's not necessarily something we need to fix this second (we have bigger fish to fry), but it's probably worth noting and fixing at some point.

**Comment by snim2** [comment]
This might be the problem:

http://stackoverflow.com/questions/23824687/text-does-not-work-in-a-matplotlib-label

**Comment by ltratt** [comment]
Ah, yes, maybe we're supposed to use `mathrm`. Honestly, I can't remember all of LaTeX/TeX's arbitrary rules :(

**Comment by snim2** [comment]
Second go:

[test_machine_name.pdf](https://github.com/softdevteam/warmup_experiment/files/587989/test_machine_name.pdf)

**Comment by ltratt** [comment]
Ah, yes, I now see, this is a bug in matplotlib's rendering. `mathrm` is a bit uglier in the paper, but in a way we can live with. So let's go with this change, and I'll adjust the paper too.

**Comment by ltratt** [comment]
So if you squash, I can merge?

**Comment by snim2** [comment]
Splat

**Review by ltratt — APPROVED** [review]

**Pull request merged**
