### PR TITLE
Fix rect collision

### LINKED ISSUE #302: Tweak needed in rect collision algorithm
The current rect collision algorithm (used for inset placement) looks to see whether any data which overlaps the rect on the x-axis has its y-value between the top and bottom of the rect.

This fails to catch cases where a measurement passes straight through the rect, for example:

rect_collision_bug

### PR DESCRIPTION
**Pull request by snim2**
Fixes #302 

### Test cases

Da capo before: [before.pdf](https://github.com/softdevteam/warmup_experiment/files/735612/before.pdf)

Da capo after: [after.pdf](https://github.com/softdevteam/warmup_experiment/files/735613/after.pdf)

[Bencher 3](https://dl.dropbox.com/s/bn9htlyoxrupgh3/fix_rect_collision_0.pdf?dl=0)

### CODE REVIEW

**Comment by vext01** [comment]
Makes sense to me. Seems to work and the code looks if anything simplified.

**Comment by snim2** [comment]
Great, let's wait for Laurie before merging though.

**Comment by ltratt** [comment]
Fine with me!

I'm not sure why the the CC axes now have a ⇑on the y axis though, or did I miss that change earlier?

**Comment by snim2** [comment]
I don't know either but it looks like some unicode has messed up the LaTeX. Have raised #322

**Comment by ltratt** [comment]
Do you want to squash or merge as-is?

**Comment by snim2** [comment]
As-is please

**Review by ltratt — APPROVED** [review]

**Pull request merged**
