### PR TITLE
Docs for krun users

### PR DESCRIPTION
**Pull request by snim2**
**NOT READY FOR REVIEW**

Just raising this PR so @fsfod can easily follow along with the commits.

### CODE REVIEW

**Comment by snim2** [comment]
This PR is waiting on #442 to be merged....

**Comment by snim2** [comment]
Ok, this is ready for review...

**Comment by ltratt** [comment]
Could we maybe add double blank lines before major section headings, just to make it easier to read in text (i.e. non-markdown) form? Otherwise this looks good to me.

**Comment by snim2** [comment]
OK to squash?

**Comment by ltratt** [comment]
Tom's going to give this a quick once-over.

**Comment by fsfod** [comment]
I was going to comment on environment variables stuff but i guess its not an issue now?

**Comment by snim2** [comment]
No, we merged a fix for the environment variable stuff. It might be worth you generating a table or two just to double-check that the advice here does work!

**Comment by fsfod** [comment]
That was all i really had and didn't really see anything wrong.

**Comment by snim2** [comment]
Thanks @fsfod 

OK to squash?

**Comment by fsfod** [comment]
yes

**Comment by snim2** [comment]
Squashed

**Review by ltratt — APPROVED** [review]

**Pull request merged**
