### PR TITLE
Skip a crashing benchmark.

### PR DESCRIPTION
**Pull request by vext01**
OK?

### CODE REVIEW

**Comment by ltratt** [comment]
I think the comment should be `XXX`'d so that we remember to come back and fix it?

**Comment by vext01** [comment]
Threw in some XXXs.

OK?

**Comment by ltratt** [comment]
Normally the `XXX`s come at the beginning of a comment. Let's fix that, squash, then I can merge.

**Comment by vext01** [comment]
Here.

**Comment by ltratt** [comment]
Perfect!

**Pull request merged**
