### PR TITLE
Fix path manipulation.

### LINKED ISSUE #170: Fix PYTHONPATH in scripts
We should be doing this:

``` python
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
```

### PR DESCRIPTION
**Pull request by snim2**
Fixes #170

### CODE REVIEW

**Comment by snim2** [comment]
@cfbolz to merge

**Comment by cfbolz** [comment]
LGTM. @vext01, @ltratt?

**Review by cfbolz — APPROVED** [review]

**Comment by vext01** [comment]
Sure, if you tested it and it works.

**Comment by ltratt** [comment]
Not a single thing in there offends me. I think that means it's good :)

**Pull request merged**
