### PR TITLE
Fix startup

### PR DESCRIPTION
**Pull request by cfbolz**
This pull request syncs `startup.krun` to the changes that were done in krun. The core approach of how startup is measured stays the same. The pull request also makes `startup.krun` contain considerably less copy-pasted code, which means it should be more robust to future changes.

### CODE REVIEW

**Comment by vext01** [comment]
```
# sudo -u krun nice -20 taskset 0x2 env <some variables> \
# outer_startup_runner_c jruby startup_runner.rb
```

This is now out of date. We don't pin, so I wouldn't expect `taskset`. I would just elide this part perhaps(?)

**Comment by cfbolz** [comment]
Yeah, as this is just to illustrate the approach, just I just kill everything up to the call to `env`?

**Comment by vext01** [comment]
Works for me.

**Comment by vext01** [comment]
This looks good.

This probably doesn't matter, but why does `patch_platform` accept an instance. Why don't we just lookup the class directly?

**Comment by vext01** [comment]
P.S. I'm going to test this now.

**Comment by cfbolz** [comment]
We could patch all platform classes, I guess?

**Comment by vext01** [comment]
I guess I expected to patch the `krun.platform` class directly in such a way that all instances are patched. If it's annoying, never mind though.

**Comment by cfbolz** [comment]
But it _is_ the class that is patched. However, to find out which class to patch (Linux, BSD, whatever), I run platform detection first.

**Comment by vext01** [comment]
Ah yes. Very good :)

**Comment by cfbolz** [comment]
so, we wait for the test, then merge?

**Comment by vext01** [comment]
Yeah, just testing it...

**Comment by vext01** [comment]
I might be being dumb, but the results should be deltas of monotonic clock values (i.e. seconds), right? The results look too large:

```
 "data": {
  "binarytrees:C:default-c": [
   [
    1176.679015,
    1176.679245
   ],
   [
    1182.930025,
    1182.930286
   ]
  ]
...
```

**Comment by cfbolz** [comment]
no, you need to substract the two numbers to get the seconds

**Comment by cfbolz** [comment]
(as the comment explains)

**Comment by vext01** [comment]
I get it. So each "execution" is really a start and stop time.

It was unfortunate that I chose a value of 2 for `N_EXECS`. Managed to confuse myself.

**Comment by cfbolz** [comment]
ah :-)

**Comment by vext01** [comment]
Add `build-startup` to the `all` target in the `Makefile` and we can merge.

**Comment by cfbolz** [comment]
like this?

**Comment by vext01** [comment]
You got it.

Want to squash?

**Comment by cfbolz** [comment]
done

**Comment by vext01** [comment]
Cheers!

**Comment by cfbolz** [comment]
cool, thanks

**Pull request merged**
