### PR TITLE
Script to count pexecs given a list of results files.

### PR DESCRIPTION
**Pull request by vext01**
In response to a comment in the paper, here is a script to count how many pexecs we have, and thus how many plots we would have to inspect by hand if we didn't have automation.

The answer is:
```
========================================================================                
GRAND TOTAL: 3660                                                    
========================================================================
```

May as well put this in the repo.

### CODE REVIEW

**Comment by ltratt** [comment]
Are there any other things we need to count for the paper? If not, this looks good!

**Comment by ltratt** [comment]
One additional comment: this script looks like it's printing *lots* of stuff to stdout. Is that useful? I guess not, in which case I'd just as soon it didn't print anything out other than the total.

**Comment by vext01** [comment]
We can add additional counts later if we need any.

I deliberately printed lots of counts as it lets me verify that there are either 30 or 0 (for skipped) pexecs per key.

**Comment by ltratt** [comment]
Verifying-by-eye sucks: can we not add `asserts`?

**Comment by vext01** [comment]
We could do yeah, but then we'd need a way to specify what to check and this raises questions like "do other users want to vary the number fo pexecs on a per-machine basis?", "do other users want to vary the number of pexecs on a per vm basis?" etc.

It doesn't take long to skim down the list tbh. I made the numbers all line up.

**Comment by vext01** [comment]
I also don't think we should over-engineer this, with so many more important tasks on the stack ;)

**Comment by ltratt** [comment]
Point taken. I'm just a bit allergic to incontinent scripts in general!

Will merge.

**Review by ltratt — APPROVED** [review]

**Comment by vext01** [comment]
Thanks

**Pull request merged**
