### PR TITLE
Update for 1 0

### PR DESCRIPTION
**Pull request by vext01**
Here are the necessary changes for the warmup experiment repo in light of the new AMPERF stuff.

This is, as yet, untested, so please don't merge.

### CODE REVIEW

**Comment by ltratt** [comment]
Looks reasonable.

**Review by ltratt — APPROVED** [review]

**Comment by vext01** [comment]
This is ready for squashing if you think the last commit looks OK.

**Comment by ltratt** [comment]
Is the last commit tested on OpenBSD? I can't quite tell from the PR, but I wonder if one gets a `AMPERF_RATIO_BOUNDS not defined` error?

**Comment by vext01** [comment]
It is indeed tested on OpenBSD.

**Comment by ltratt** [comment]
Ok, then please squash.

**Comment by ltratt** [comment]
BTW, I think `extbench/rundacapo.py` and `extbench/runoctane.py` also need bencher2 -> bencher8 fixing?

**Comment by vext01** [comment]
squashed.

**Comment by vext01** [comment]
ah, lets do those now too...

**Comment by ltratt** [comment]
Agreed.

**Comment by vext01** [comment]
Forced into first commit.

**Comment by vext01** [comment]
(yeah, i know, naughty) ;)

**Comment by ltratt** [comment]
OK to merge then?

**Comment by vext01** [comment]
Please.

**Pull request merged**
