### PR TITLE
Report summary macros for good/bad inconsistency.

### LINKED ISSUE #339: Add "good" and "bad" inconsistent macros to macro summary script

### PR DESCRIPTION
**Pull request by snim2**
Fixes #339 

Output of v0.7 data: [summary_macros.txt](https://github.com/softdevteam/warmup_experiment/files/813730/summary_macros.txt)

### CODE REVIEW

**Comment by ltratt** [comment]
Can you stick in a quick PDF of table 1? My ability to read this sort of LaTeX is low ;)

**Comment by snim2** [comment]
I wasn't quite sure what you wanted in terms of the paper and tables. This is a first effort: [table1_from_paper.pdf](https://github.com/softdevteam/warmup_experiment/files/814591/table1_from_paper.pdf)

I have given you macros here for "inconsistent (both types)", "good inconsistent" and "bad inconsistent". The sparklines make that a bit confusing in the table, so this probably isn't *exactly* what you want for the final paper.

**Comment by ltratt** [comment]
I think we want just "good inconsitent" and "band inconsistent" in the paper (the two combined isn't really helpful, because the two types are very different IMHO), which should also make the (VM, benchmark) pair columns add up to 100%.

**Comment by snim2** [comment]
Possibly a silly question, but the paper we have things like this:

```latex
On \bencherthree
\bencherthreevmbenchpairsslowdownpercentage\% of \vmbpair pairs slowdown
and \bencherthreevmbenchpairsinconsistentpercentage\% are inconsistent
(with over two thirds of those being obviously `bad'); \bencherfive and
\benchersix are broadly similar.
```

are you going to want to re-write that text, or should I leave the `\inconsistent` macros in?

**Comment by ltratt** [comment]
Factoring out good and bad inconsistency will mean we need to rewrite quite a few of those bits. The basic problem is that we assume that bad inconsistency is just that: definitely bad. However, good inconsistency is a little fuzzier: it *could* be bad, but we're giving JITs the benefit of the doubt (because it could be the result of limitations in our classification).

**Comment by snim2** [comment]
Next table: [table1_from_paper_no_inconsistent.pdf](https://github.com/softdevteam/warmup_experiment/files/814652/table1_from_paper_no_inconsistent.pdf)

You might notice that the numbers here are not the same as the numbers in the paper. I've had a look at this, and I'm pretty sure that the version of the macros in the paper included the empty benchmark, and that's why they are different.

**Comment by ltratt** [comment]
So I think we can merge this one? Does it need squashing?

**Comment by snim2** [comment]
Yes...

**Comment by snim2** [comment]
Ok, all squashed

**Review by ltratt — APPROVED** [review]

**Pull request merged**
