### PR TITLE
Add python-dev to prerequisites.

### PR DESCRIPTION
**Pull request by snim2**
What it says on the tin.

### CODE REVIEW

**Comment by ltratt** [comment]
Are we definitely very sure we need this? I assume this is for `Python.h` or something? What actually uses that?

**Review by vext01 — APPROVED** [review]

**Comment by vext01** [comment]
It's an R extension.

**Comment by ltratt** [comment]
Ah is this for the "link Python to R" stuff?

**Comment by snim2** [comment]
I had to install this on bencher3 before the build_stats script could work.

**Comment by ltratt** [comment]
Yes, but I just want to briefly understand what it fixed.

**Comment by snim2** [comment]
Ah, as Edd said, the R packages could not be compiled without it.

**Comment by vext01** [comment]
I suppose R embeds Python? Is that the case Sarah?

**Comment by ltratt** [comment]
"R needs Python" just seems a bit weird on the face of it right?

**Comment by snim2** [comment]
We use `r2py` which calls R from Python, but R probably does embed it also.

**Comment by ltratt** [comment]
Right, so `r2py` sounds very plausible. Makes sense.

**Comment by vext01** [comment]
Sorry, that's what I meant. r2py causes R to embed Python.

**Pull request merged**
