### PR TITLE
Clean up usage of gmake.

### PR DESCRIPTION
**Pull request by vext01**
Don't merge yet. Needs a rebuild on Linux and OpenBSD to check for problems.

Looks OK?

### CODE REVIEW

**Comment by ltratt** [comment]
Do we want to do some squashing before merging?

**Comment by vext01** [comment]
Isn't this my responsibility this time?

**Comment by vext01** [comment]
Ah yes, I see. Yes I will squash.

**Comment by ltratt** [comment]
(And rebase against master, if necessary)

**Comment by vext01** [comment]
splat.

**Pull request merged**
