### PR TITLE
Disable SSH when benchmarking.

### PR DESCRIPTION
**Pull request by vext01**
Tested on bencher7 over idrac.

OK?

### CODE REVIEW

**Comment by snim2** [comment]
Looks OK. How did you test this? And, do you want to merge?

**Comment by vext01** [comment]
I used bencher7. Logged in the idrac console, ran the experiment, and observed that my SSH connection had locked up (which it should anyway since the network is downed too) and that the debug log showed the ssh daemon going down.

**Comment by snim2** [comment]
Ok, cool. Do you want to squash?

**Comment by vext01** [comment]
splat

**Review by snim2 — APPROVED** [review]

**Pull request merged**
