### PR TITLE
Allow changepoint-related plot annotations to happen with --wallclo-only and -b.

### PR DESCRIPTION
**Pull request by vext01**
Hi @snim2 I think this is the fix. Just de-dent these two blocks.

Testing a bit now...

### CODE REVIEW

**Comment by snim2** [comment]
Worth testing with as many combinations of CLI options as you can :(

**Comment by vext01** [comment]
I'm hoping it's harmless enough, as it only ever adds to the data dictionaries... Still... Plot script will find a way to make me sad, I'm sure.

**Comment by vext01** [comment]
Confirmed this only affects runs with `-b` btw.

**Comment by snim2** [comment]
Great, I was just about to ask.

**Comment by vext01** [comment]
I think this is good, but I found an unrelated bug. Will file.

**Comment by snim2** [comment]
Ready to merge?

**Review by snim2 — APPROVED** [review]

**Comment by vext01** [comment]
Yeah, go ahead.

**Pull request merged**
