### PR TITLE
Correct typo in subplot titles.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by vext01** [comment]
(yeh, sorry this took so long)

I did consider it, but thought it would be more maintainable to have them explicit. By all means prove me wrong though.

**Comment by snim2** [comment]
Well, if it works let's leave it like this for now and we can come back to it in the next round of changes if we still feel it needs some tidying.

**Comment by vext01** [comment]
OK, mind if i squash?

**Comment by snim2** [comment]
Sure, go ahead

**Comment by vext01** [comment]
ok, if you are happy, merge away.

**Comment by vext01** [comment]
Thanks

**Pull request merged**
