### PR TITLE
Fix .PHONY

### PR DESCRIPTION
**Pull request by vext01**
OK?

### CODE REVIEW

**Comment by ltratt** [comment]
I think I see the problem: shouldn't it be `.PHONY`?

**Comment by ltratt** [comment]
See https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html#Phony-Targets

**Comment by vext01** [comment]
oh, oh, oh! :P Woops.

**Comment by vext01** [comment]
Fixed. Can I squish?

**Comment by ltratt** [comment]
Just to confirm: this definitely solves the problem that running make ran the wrong rules? Assuming so, squash, and then I'll merge.

**Comment by vext01** [comment]
Correct -- squashed -- merge at will.

**Pull request merged**
