### PR TITLE
Improve y-tick labels

### LINKED ISSUE #306: Scientific ticklabels are too complicated
The y-tick formatter applies scientific formatting to y-axis of a given set of axes, it changes the ticklabels from 'offset' notation (where a number is added / subtracted to each ticklabel) to the more intuitive scientific notation (where a number multiplies each ticklabel). It then removes the multiplier from the top-left hand corner of the plot, and add it to the ticklabel instead.

However, we sometimes get very complex ticklabels like this:

`0. 046 x 10^4 +9. 299x10^-1`

which are too complicated.

### PR DESCRIPTION
**Pull request by snim2**
Fixes #306 

### Before / after tests

See page 3:

  * Before: [test_ticks_before.pdf](https://github.com/softdevteam/warmup_experiment/files/714572/test_ticks_before.pdf)
  * After: [test_ticks.pdf](https://github.com/softdevteam/warmup_experiment/files/714573/test_ticks.pdf)

See page 52:

  * Before: [bencher3_test_ticks_before.pdf](https://github.com/softdevteam/warmup_experiment/files/714605/bencher3_test_ticks_before.pdf)
  * After: [bencher3_test_ticks_after.pdf](https://github.com/softdevteam/warmup_experiment/files/714735/bencher3_test_ticks_after.pdf)

### Other test cases

  * Da capo: [test_ticks_dacapo.pdf](https://github.com/softdevteam/warmup_experiment/files/714571/test_ticks_dacapo.pdf)

### CODE REVIEW

**Comment by ltratt** [comment]
Two obvious questions. First, what does "most" mean ;) Second, can we fix the number of DP? On the "small" example, the DP for the main plots is 5, 4, 7 (!), 6 for pages 1, 2, 3, 4 respectively. I would like to think we could get away with 4DP, but 5DP is probably the maximum we can show without people laughing at us. [Some of the timers / float representations (e.g. Octane/V8) are only accurate to 6DP anyway it seems. I don't know about other VMs though.]

**Comment by snim2** [comment]
Re "many": I have turned "offsets" off. Offsets are the text that read 10^... that used to appear on the top-left of the axes. I would have thought that turning off offsets would turn them off, in fact it turns them off *sometimes*. So I guess that turning them on meant "please have an offset even if it is completely unnecessary to do so".

**Comment by ltratt** [comment]
Erk. OK, I guess we can see if that problem does actually happen in practise. Maybe we'll get lucky!

If we can sort out the DP thing, then I think we'll be good to merge.

**Comment by snim2** [comment]
There isn't a way to do what you want. This next round of test cases uses the following:

  * If the ticklabels are reasonably small (i.e. they are likely to fit in 5sf) then use a simple string formatter
  * Otherwise use the more complex formatter with the offset

Potentially we might still get a case where the formatter gives us a complex offset, but this change should make that very unlikely.

  * Small test: [test_ticks_after.pdf](https://github.com/softdevteam/warmup_experiment/files/716303/test_ticks_after.pdf)
  * Da capo test: [test_ticks_dacapo.pdf](https://github.com/softdevteam/warmup_experiment/files/716304/test_ticks_dacapo.pdf)
  * Bencher 3 test: [bencher3_test_ticks_after.pdf](https://github.com/softdevteam/warmup_experiment/files/716306/bencher3_test_ticks_after.pdf)

**Comment by ltratt** [comment]
If I look at the small & dacapo files, everything is 5DP except xalan and fop which are 3DP. Any ideas why?

**Comment by snim2** [comment]
Try this: [xalan.pdf](https://github.com/softdevteam/warmup_experiment/files/716446/xalan.pdf)

**Comment by ltratt** [comment]
Aha, perfect! Do we need to check it on all the others, or are we fairly sure that everything that reasonably can be 5DP will be 5DP?

**Comment by snim2** [comment]
The problem was caused by a condition: `if y_max > 100000 or y_min < 0.00001:` was being triggered to use the scientific formatting because `y_min` was `0.0`. The condition is now:

```
    if y_max > 100000 or (y_min < 0.00001 and y_min > 0.0):
```

so other cases should not be affected.

**Comment by ltratt** [comment]
Is that a "yes"? ;)

**Comment by snim2** [comment]
Yes, the other pages should be unaffected.

**Comment by ltratt** [comment]
Excellent! OK, squash as you see fit, then I can merge.

**Comment by snim2** [comment]
Squashed.

**Comment by ltratt** [comment]
Thanks!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
