### PR TITLE
Automatically compute iterations which should be placed in an inset

### PR DESCRIPTION
**Pull request by snim2**
Algorithm as follows:
  * Use the first 2.5% of the iterations (50 iterations on a run of 2000)
  * If all changepoints occur in the first 5% of iterations (100 iterations on a run of 2000) then the inset plots up to the last changepoint + 2% of the iterations.
  * Clamp the above to a largest extent of 0->150 iterations.

Test case: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/634409/test_insets.pdf)

Needs squashing.

### CODE REVIEW

**Comment by vext01** [comment]
Sounds reasonable, but I'll let Laurie give the final word.

**Comment by ltratt** [comment]
On p1 the insets x axis only goes up to 45, but actually seems to plot 43 or 44 iterations?

**Comment by vext01** [comment]
Maybe an example PDF would help?

**Comment by snim2** [comment]
Hang about, I haven't finished yet!

**Comment by ltratt** [comment]
OK.

**Comment by vext01** [comment]
Sorry :jack_o_lantern:

**Comment by snim2** [comment]
OK, the code now tries to detect whether the inset will collide with data. In this testcase, both H2 and Tradebeans do collide: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/634577/test_insets.pdf)

**Comment by ltratt** [comment]
I can't see why tradebeans collides with anything (though H2 definitely does).

[Repeating the premature comment] On p1 the insets x axis only goes up to 45, but actually seems to plot 43 or 44 iterations?

**Comment by snim2** [comment]
Yes there seem to be a few of those, but it isn't obvious to me why it's happening....

**Comment by ltratt** [comment]
I think we need to fix those two things (tradebeans + short x axes), but otherwise this is looking very nice.

**Comment by snim2** [comment]
Also I'm not sure we will get the right x-axis on the inset if we use `--xlimits` on the command line.

**Comment by ltratt** [comment]
I'm happy for the manual option to be killed, at least for the time being.

**Comment by snim2** [comment]
I mean, if you only want to plot iterations A-B on the main plot, you will get a silly inset.

**Comment by snim2** [comment]
OK, next test case: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/634711/test_insets.pdf)

**Comment by ltratt** [comment]
The x axis in the insets is now clearly wrong even on p1: 8?!

**Comment by snim2** [comment]
OK, try again: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/634848/test_insets.pdf)

**Comment by snim2** [comment]
Test case: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/634889/test_insets.pdf)

**Comment by ltratt** [comment]
This is looking close to done. One final thing: the time-series data starts on the LHS of the x axis, but looks like it finishes at entry 49 (not 50) on the RHS. Any thoughts?

**Comment by snim2** [comment]
Try this: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/635255/test_insets.pdf)

**Comment by ltratt** [comment]
Perfect! Let's squash, then I can merge.

**Comment by snim2** [comment]
Squashed!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
