### PR TITLE
Use argparse to check CLI options.

### PR DESCRIPTION
**Pull request by snim2**
**TODO** This branch should be merged before splitting the repo.

### CODE REVIEW

**Comment by snim2** [comment]
The current commit in this PR is very old, and the branch needs bringing up to date. Is it OK to force-push this now?

**Comment by ltratt** [comment]
Feel free to do a rebase.

**Comment by snim2** [comment]
Rebased. This needs some more testing then it will be ready to merge.

**Comment by snim2** [comment]
This PR was intended to "fix" #381, which reported a "crash" in the plotting script. That "crash" was caused by passing in invalid parameters to the script. The fix proposed in this PR changes the CLI options of the plotting script quite radically and uses the `argparse` library to check that valid options will be passed in. It has the complication of not comma-separating lists of arguments, e.g.:

```
... --core-cycles 1, 2, 3 -x 100, 150 ...
```

would become:

```
... --core-cycles 1 2 3  -x 100 150 ...
```

which makes the CLI options trickier to parse, and will require us to re-write parts of the `Makefile` in the other repo, the `warmup_stats` script, and so on. 

I'm minded to think that this PR should be closed without merging, because it needs a much more careful rethink if we are going to use `argparse` in this way in the future.

**Comment by ltratt** [comment]
Agreed -- let's close it and rethink later.

**Pull request closed without merging**
