### PR TITLE
Fix insets

### LINKED ISSUE #191: Fix --inset-xlimits
This has been broken by introducing `GridSpec` style charts, rather than the old calls to `subplot()`. The problem we have is that our code calls `axis.transAxes.transform()` to make the size of the inset plot small enough to fit inside the wallclock time chart. 

Maybe we can find a way around this, but if not we may have to add the "thumbnail" plot to the stack of larger plots, rather than embedding it inside the wallclock plot.

Other ideas welcome...

### PR DESCRIPTION
**Pull request by snim2**
Needs squashing.

This isn't a very tidy solution, but we will refactor soon anyway, so it will do for now!

Test case: [test_insets.pdf](https://github.com/softdevteam/warmup_experiment/files/634169/test_insets.pdf)

Fixes #191

### CODE REVIEW

**Comment by vext01** [comment]
Looks good. Well done!

Remind me, are the visibility and xrange of the insets still configurable?

**Comment by snim2** [comment]
Syntax is: `--inset-xlimits START_ITER,END_ITER` 
Placement is not configurable.

**Comment by vext01** [comment]
And if you don't specify `--inset-xlimit`, you get no inset, right?

I think that's OK for now.

**Comment by snim2** [comment]
That's right, default is not to have the inset at all

**Comment by vext01** [comment]
Go ahead and squash.

**Comment by ltratt** [comment]
This looks nice. I think, by default, 200 iterations is too many to show though, as the shape is lost a little bit. I'd like to suggest trying the following: default to displaying 50 iterations; if all of the changepoints in the file are <= iteration 100, then display up to the final changepoint + 25 iterations; but the absolute max is (say) 125 iterations.

We'll probably need to fiddle to get this looking good, but something like this seems plausibly useful.

**Comment by snim2** [comment]
The number of iterations and the extent of them is passed in on the command line, e.g. `--inset-xlimits 0,100`, the attachment was just an example.

**Comment by ltratt** [comment]
A fixed number of iterations won't often be useful, so let's default to doing something automatic that does a decent job in most cases.

**Comment by vext01** [comment]
Suggest making that a separate PR?

**Comment by ltratt** [comment]
It's a pretty small feature. I don't see that it's worth creating a new PR for.

**Comment by ltratt** [comment]
On reflection, I see what you both mean. OK, let's squash this, then create a new PR for the "auto-sizing" and "auto-placement" stuff.

**Review by ltratt — APPROVED** [review]

**Comment by snim2** [comment]
Squashed

**Pull request merged**
