### PR TITLE
Dashed cpts

### PR DESCRIPTION
**Pull request by snim2**
This PR paints changepoints and segment means with dashed lines rather than solid. For example: 
[dashed.pdf](https://github.com/softdevteam/warmup_experiment/files/862191/dashed.pdf)

### CODE REVIEW

**Comment by vext01** [comment]
Excellent. That makes the plots much easier to read. Many thanks.

@ltratt OK with this?

**Comment by snim2** [comment]
Needs squashing BTW

**Comment by ltratt** [comment]
Works for me!

**Comment by ltratt** [comment]
Works for me!

**Comment by vext01** [comment]
squash away, and then feel free to merge, as I'm just going AFK

**Comment by snim2** [comment]
Squashed!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
