### PR TITLE
Various updates (including PyPy 4.0 and OpenBSD fixes)

### PR DESCRIPTION
**Pull request by ltratt**
This is ready for comments, but not for merging. I am doing some final testing on bencher5 and bencher6 (should be done early this evening if I'm lucky).

### CODE REVIEW

**Comment by vext01** [comment]
Looks OK so far.

**Comment by ltratt** [comment]
The build eventually dies on OpenBSD with http://pastebin.com/fyM4MY2A -- but I think this is partly to be expected (the krun config file is trying to do stuff with Graal, and that doesn't exist). I'll leave that for you to deal with in a separate PR :)

**Comment by ltratt** [comment]
OK, this builds fine on bencher5 (until it complains about the lack of a tickless kernel) and bencher6 (modulo the error noted earlier). I think it can be merged.

**Comment by vext01** [comment]
WRT the errors you are seeing, it's indeed because you don't have graal jvmci in the work dir.

I would expect a better error message though. Will look into that.

In the meantime, in the warmup experiment config file, you should put guards around the VMs you don't expect to work on openbsd.

**Comment by ltratt** [comment]
Can I leave the guards to you (possibly in a separate PR)? I don't know how to do that.

**Comment by vext01** [comment]
I can do it if you like, but it shouldn't be hard and it is better tested on the real openbsd environment.

Remember, the config file is just a Python script, so you can add `if not sys.platform.startswith(...)` guards to prevent definitions of VMs.

**Comment by ltratt** [comment]
You can do this about 10x faster than me -- I've never really looked at the config file! You can tack it onto this PR if you want and I'll test it. [Sarah would then need to do the merging.]

**Pull request merged**
