### PR TITLE
Use TruffleRuby as the VM's name.

### PR DESCRIPTION
**Pull request by ltratt**
This changed underneath us a couple of times and we didn't consistently update
it.

### CODE REVIEW

**Comment by snim2** [comment]
Let me test this before merging...

**Comment by ltratt** [comment]
OK.

**Comment by snim2** [comment]
I'm still seeing "JRubyTruffle" in plot titles, so I think there's a change missing here?

**Comment by ltratt** [comment]
If I `grep` over the repo after this branches changes I get this:

```
$ grep -r JRubyTruffle *
bin/table_classification_summaries_main:    'JRubyTruffle': 'TruffleRuby',
```

Maybe it's using the key rather than value for the graph titles?

**Comment by snim2** [comment]
`plot_krun_results` lines 1196 and 1302 are the droids you are looking for ...

**Comment by ltratt** [comment]
OK, let me look.

**Comment by ltratt** [comment]
Right, I think I see. I have no way of testing any changes. Might you be able to propose a fix? We can review each other's changes and maybe ask Edd to merge.

**Comment by snim2** [comment]
I tested the plots with:

```sh
./bin/plot_krun_results  -w 100  --export-size 5,5 -o truncated1.pdf -b bencher7:binarytrees:JRubyTruffle:default-ruby:3 --no-zoom --wallclock-only --with-changepoint-means --with-outliers --no-inset save_truncate/truncated_1000_outliers_w100_changepoints.json.bz2

./bin/plot_krun_results  -w 105  --export-size 5,5 -o truncated2.pdf -b bencher7:binarytrees:JRubyTruffle:default-ruby:3 --no-zoom --wallclock-only --with-changepoint-means --with-outliers --no-inset save_truncate/truncated_1050_outliers_w105_changepoints.json.bz2
```

Might be a good idea if @vext01 tries something different...

**Comment by ltratt** [comment]
It certainly looks reasonable to me.

**Comment by vext01** [comment]
Looks like Sarah has this under control :)

**Comment by snim2** [comment]
I think so, it just needs someone else to review, since I pushed to this branch :)

**Comment by ltratt** [comment]
@vext01 I think we're looking for an OK from you (neither Sarah nor I can merge this PR).

**Comment by vext01** [comment]
I don't see anything out of place. Ready to merge?

**Comment by ltratt** [comment]
I think so.

**Review by vext01 — APPROVED** [review]

**Pull request merged**
