### PR TITLE
Ignore auto-generated files from C benchmarks.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by ltratt** [comment]
Does `spectralnorm` not also create a `.so`?

**Comment by snim2** [comment]
Ready for squashing?

**Comment by ltratt** [comment]
Yep, squash away!

**Comment by ltratt** [comment]
Ready to merge?

**Comment by snim2** [comment]
yep, good to go

**Comment by snim2** [comment]
Ta

**Pull request merged**
