### PR TITLE
Pass LD_LIBRARY_FLAGS to octane. Skip spidermonkey on OpenBSD.

### PR DESCRIPTION
**Pull request by vext01**
Fixes crashes on OpenBSD.

Tested on OpenBSD, but can you try testing this branch on Linux. I don't have the VMs built at the moment (also comment out v8 to check the spidermonkey invocation too).

Thanks

### CODE REVIEW

**Comment by ltratt** [comment]
Testing on bencher2 now (this will take quite a while).

**Comment by vext01** [comment]
In case it helps, it's probably enough to check that each VM is using a lot of CPU. If it's going to crash it's at load time.

**Comment by ltratt** [comment]
There are quite a lot of safeguards to override: I'd prefer to run it properly (will be done by the end of today).

**Comment by vext01** [comment]
no worries.

**Comment by vext01** [comment]
Any news on this?

**Comment by ltratt** [comment]
Oops, yes, it passed. Sorry & thanks!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
