### PR TITLE
Move to our new licensing regime.

### PR DESCRIPTION
**Pull request by ltratt**
All copyright in this project is held by King's, so moving it is trivial.

### CODE REVIEW

**Comment by vext01** [comment]
There's licensing info in README.md which could probably be removed now.

**Comment by ltratt** [comment]
Good point. Fixed in https://github.com/softdevteam/warmup_experiment/pull/473/commits/04d5573b3e0c433f9772a59ac2264bc4a9813429.

**Comment by vext01** [comment]
LGTM, please squash.

**Comment by ltratt** [comment]
Squashed.

**Review by vext01 — APPROVED** [review]

**Pull request merged**
