### PR TITLE
New TSR interfaces for VMs.

### PR DESCRIPTION
**Pull request by vext01**
In response to: https://github.com/softdevteam/krun/pull/238

Note that the new TSR functions now all use libkruntime instead of duplicating code in the VM itself. The support code was getting large and I was worried that we might end up in a situation where the code falls out of sync between VMs and libkruntime.

There is still duplication WRT `clock_gettime_monotonic`, but I will raise a separate PR to fix that next (make them use libkrun too).

Note the ruby support is special. It now always returns a Ruby `Bignum`.

OK?

### CODE REVIEW

**Comment by vext01** [comment]
And how about this one? We should merge the two PRs at the same time.

**Comment by cfbolz** [comment]
looks good to me. do you want to splat?

**Comment by vext01** [comment]
I reckon it is OK as-is.

Let Laurie OK before merge.

**Comment by vext01** [comment]
Or not :P

**Comment by ltratt** [comment]
The Truffle part looks a bit heavyweight, calling `getcontext` and so on -- is that fair? I wonder if we can cache the libkruntime somewhere, and then just call the TSR function?

**Comment by vext01** [comment]
Raise a bug and I will look tomorrow.

**Comment by ltratt** [comment]
It's not a bug necessarily...

**Comment by vext01** [comment]
Might be able to cache it locally in the constructors.

**Comment by ltratt** [comment]
Yes, that's the sort of thing I was thinking of.

**Pull request merged**
