### PR TITLE
Plots without changepoints are coloured black.

### LINKED ISSUE #406: Plotting without changepoints makes the plot gray.
Should it be black?

### PR DESCRIPTION
**Pull request by snim2**
Fixes #406 

Test case: [test_gray.pdf](https://github.com/softdevteam/warmup_experiment/files/1019161/test_gray.pdf)

### CODE REVIEW

**Comment by snim2** [comment]
Needs squashing.

**Comment by ltratt** [comment]
Yep, let's squash and I can merge.

**Comment by vext01** [comment]
seems good to me

**Comment by snim2** [comment]
Splat.

**Review by ltratt — APPROVED** [review]

**Pull request merged**
