### PR TITLE
Move INSTALL.md to stats repo.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by ltratt** [comment]
Hmmm, but we still need *some* sort of install instructions here don't we? Maybe @vext01 has a thought or two on that?

**Comment by vext01** [comment]
I tend to think that you need some brief instructions on how to get started.

It usually amounts to running `build.sh` (perhaps mention the `-f` flag), `make build-benchmarks`, `make build-krun` and then running Krun on one of the config files.

The `Makefile` in this repo has tons of targets I never use. Perhaps we should GC some?

**Comment by snim2** [comment]
Possibly, there are a few getting started things in the current README...

**Comment by ltratt** [comment]
Let's resurrect this, as I think it will be a useful PR.

**Comment by ltratt** [comment]
@snim2 Thoughts?

**Comment by snim2** [comment]
It isn't totally obvious to me what we need to keep in. However, I will give it a go later today and we can debate it from there. https://github.com/softdevteam/warmup_stats/pull/14 has resolved the first part of this issue by adding INSTaLL.md to the other repo.

**Comment by snim2** [comment]
Ready for re-review.

**Comment by ltratt** [comment]
Works for me! Squash or merge as-is?

**Comment by snim2** [comment]
Squash coming up...

**Comment by snim2** [comment]
Splat!

**Review by ltratt — APPROVED** [review]

**Pull request merged**
