### PR TITLE
New charting code

### PR DESCRIPTION
**Pull request by snim2**
The current workflow for these scripts is:

`mark_outliers_in_json.py` can be used to mark outliers (defined as data points outside 5-sigma based on a rolling mean):

``` bash
$ ./mark_outliers_in_json.py --help
usage: Write lists of outliers into Krun results file(s).
Example usage:

$ python mark_outliers_in_json.py -f results1.json.bz2
$ python mark_outliers_in_json.py -f results1.json.bz2 -f results2.json.bz2 --window 250
       [-h] [--filename JSON_FILES] [--window WINDOW_SIZE]
       [--threshold THRESHOLD]

optional arguments:
  -h, --help            show this help message and exit
  --filename JSON_FILES, -f JSON_FILES
                        Krun results file. This switch can be used repeatedly
                        to chart data from a number of results files.
  --window WINDOW_SIZE, -w WINDOW_SIZE
                        Size of the sliding window used to draw percentiles.
  --threshold THRESHOLD, -t THRESHOLD
                        If an outlier appears in more than THRESHOLD
                        executions it is said to be common to several
                        executions and is stored in the common_outliers field
                        of the JSON file, rather than the unique_outliers
                        field.
```

`outlier_summaries.py` can be used to generate LaTeX tables of the outlier data:

``` bash
$ ./outlier_summaries.py --help
usage: outlier_summaries.py [-h] --filename JSON_FILES
                            [--latexfile LATEX_FILE]

Summarise outlier information stored within a Krun results file.

Example usage:

    $ python outlier_summaries.py -f bencher_results.json.bz2
    $ python outlier_summaries.py -f results.json.bz2
 -l summary.tex

optional arguments:
  -h, --help            show this help message and exit
  --filename JSON_FILES, -f JSON_FILES
                        Krun results file. This switch can be used repeatedly to chart data from a number of results files.
  --latexfile LATEX_FILE, -l LATEX_FILE
                        Name of the LaTeX file to write to.
```

and `plot_krun_results.py` can be used to draw charts of Krun results files:

``` bash
$ ./plot_krun_results.py --help
usage: Plot data from Krun results file(s).
Example usage:

$ python plot_krun_results.py -f results1.json.bz2
$ python plot_krun_results.py -i -f results1.json.bz2 -f results2.json.bz2 --window 250 --mean --sigma --with-outliers
$ python plot_krun_results.py -b  binarytrees:Hotspot:default-java
       [-h] [--interactive] [--filename JSON_FILES] [--outfile OUTFILE]
       [--window WINDOW_SIZE] [--benchmark BENCHMARK] [--xlimits XLIMITS]
       [--single-exec SINGLE_EXEC] [--mean] [--sigma] [--with-outliers]
       [--with-unique-outliers]

optional arguments:
  -h, --help            show this help message and exit
  --interactive, -i     Display graphs (rather than writing to a file)
  --filename JSON_FILES, -f JSON_FILES
                        Krun results file. This switch can be used repeatedly
                        to chart data from a number of results files.
  --outfile OUTFILE, -o OUTFILE
                        Name of the PDF file to write to.
  --window WINDOW_SIZE, -w WINDOW_SIZE
                        Size of the sliding window used to draw percentiles.
  --benchmark BENCHMARK, -b BENCHMARK
                        Only draw charts for a specific benchmark/vm/variant
                        triplet. e.g. binarytrees:Hotspot:default-java
  --xlimits XLIMITS, -x XLIMITS
                        Specify X-axis limits as a comma separated pair
                        'start,end'. Samples start from 0. e.g. '-x 100,130'
                        will show samples in the range 100 to 130.
  --single-exec SINGLE_EXEC, -e SINGLE_EXEC
                        Emit a graph for a single process execution. e.g. '-e
                        0' emits only the first.
  --mean, -m            Draw a rolling mean.
  --sigma, -s           Draw 5-sigma interval around the rolling mean.
  --with-outliers       Annotate outliers. Only use this if your Krun results
                        file contains outlier information.
  --with-unique-outliers
                        Annotate outliers common to multiple executions and
                        those unique to single executions differently.
```

Fixes: #62

### CODE REVIEW

**Comment by snim2** [comment]
Splat.

**Comment by vext01** [comment]
Wow, this is a huge change.

I don't see anything obviously wrong and the code looks clean. If you are happy, let's move ahead?

Cheers

**Comment by snim2** [comment]
Yes, I wasn't expecting this branch to be so long lived, and many of the commits were very small. 

I've tested various combinations of charts and so on, and AFAICT no functionality has been changed by the squash.

**Comment by vext01** [comment]
OK, so good to merge?

**Comment by snim2** [comment]
Yup, fine from my POV

**Comment by vext01** [comment]
Thanks!

**Pull request merged**
