### PR TITLE
Annotate segment means

### PR DESCRIPTION
**Pull request by snim2**
This is a simple first step towards resolving #288 

Whenever a warmup or slowdown process execution has > 1 changepoint, the last and penultimate segments are annotated with their means, drawn either side of the last changepoint. 

### Small test case

[issue_288_test.pdf](https://github.com/softdevteam/warmup_experiment/files/685946/issue_288_test.pdf)

### Larger test case (v0.7)

[issue_288_test_large.pdf](https://github.com/softdevteam/warmup_experiment/files/685947/issue_288_test_large.pdf)

### CODE REVIEW

**Comment by ltratt** [comment]
For this simple version, I think we might as well just plot the means everywhere (there's no use in restricting it to warmup/slowdown). Even with this subset, we can clearly see that there are some things worthy of our attention. For example: in the small test case, jython/graal/#3 if the "merge" threshold was 0.005s (not 0.001s) this would be a warmup. That, and a few examples, are suggestive that our original threshold of 0.001s is probably too conservative (which I suspected before, but couldn't really confirm either way).

I think we'll need a nicer way of visualising than this in the long run, but this is definitely very helpful as a first step! Let's first plot the means everywhere, look at the data, then we might try bumping up the merge threshold and replotting, and see where that gets us.

[BTW, I think you might have created this branch from that for PR #292. We can either wait until we merge 292, or you might want to rebase the relevant commit against master and force push against this branch.]

**Comment by snim2** [comment]
I'm not so sure about plotting the means everywhere. Many plots have changepoints that occur closely together, which means that the mean will be obscured by the changepoint line and maybe other artists.

**Comment by ltratt** [comment]
At the moment there are many examples where I want to see what's going on, but there are no numbers. I'd prefer too many than too little, at least while we're trying to understand our data better.

**Comment by snim2** [comment]
Try this: [issue_288_test.pdf](https://github.com/softdevteam/warmup_experiment/files/686073/issue_288_test.pdf)

**Comment by ltratt** [comment]
I'm confused: this doesn't annotate all segments even on page 1?

**Comment by ltratt** [comment]
[For example, I *really* want to see the segment times on fop/graal.]

**Comment by snim2** [comment]
Warmups / slowdowns with only one changepoint are deemed "uninteresting", the Fop/Graal charts are "no steady state", so not annotated at all.

**Comment by ltratt** [comment]
At the moment we're debugging, so let's please annotate the no steady states so we can see what's going on.

**Comment by ltratt** [comment]
[Even with the limited annotations, it's clear that we need to think more carefully about when to merge segments. We can get more clever later with the "how to present this to everyone else", but at the moment I think we really need to see *all* the segment means.]

**Comment by snim2** [comment]
Next: [issue_288_test.pdf](https://github.com/softdevteam/warmup_experiment/files/687148/issue_288_test.pdf)

**Comment by snim2** [comment]
About to squash this in order to bring it up to date with master...

**Comment by snim2** [comment]
This branch now has the improved inset placements from master.

**Comment by snim2** [comment]
Bringing this up to date with master again...

**Comment by snim2** [comment]
This PR and branch was used for our debugging, and can probably be closed / deleted before we split this repo.

**Comment by ltratt** [comment]
I agree -- closing.

**Pull request closed without merging**
