### PR TITLE
Aesthetic changes

### PR DESCRIPTION
**Pull request by snim2**
This PR makes outlier markers a little bit smaller and adds a white background to insets, so their ticklabels can be seen more clearly.

[Test case](https://dl.dropbox.com/s/m786npkwqreb3j6/aesthetic_changes_0.pdf?dl=0)

### CODE REVIEW

**Comment by ltratt** [comment]
I'm more-or-less fine with this, but the big white box means we're now clipping again: see e.g. binarytrees/pypy/#8. If we can fix that, then I'm fine with merging this.

**Comment by snim2** [comment]
I'd prefer to leave that to Issue #302 if you don't mind

**Comment by ltratt** [comment]
It's not the same bug (although obviously very similar!) -- the clipping is hitting data that the rectangle wholly overwrites. You can add it as a secondary part of 302 if you want though.

**Comment by snim2** [comment]
Yup, although the bugs are different, the fix will be that the rect collision code needs another re-write.

**Comment by ltratt** [comment]
OK.

**Review by ltratt — APPROVED** [review]

**Pull request merged**
