### PR TITLE
Disable Graal on OpenBSD when running DaCapo.

### PR DESCRIPTION
**Pull request by ltratt**
Warning: untested. Please confirm whether it works or not!

### CODE REVIEW

**Comment by vext01** [comment]
You need to ensure `find_internal_jvmci_java_home` only happens on linux too. It will crash out because it can't find it on openbsd.

**Comment by ltratt** [comment]
Done.

**Comment by vext01** [comment]
That fixes graal. Please go ahead and squash.

Something else (unrelated) is crashing, which we could do in a separate PR:

```
...
PYTHONPATH=krun/ JAVA_HOME=/home/kruninit/warmup_experiment/work/openjdk/build/bsd-x86_64-normal-server-release/images/j2sdk-image python2.7 extbench/rundacapo.py
hotspot:
  avrora: 0ERROR:root:Command failed: '$JAVA_HOME/bin/java -jar extbench/dacapo-9.12-bach.jar avrora -n 2001'
stdout:

stderr:
Error: dl failure on line 902
Error: failed /home/kruninit/warmup_experiment/work/openjdk/build/bsd-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/server/libjvm.so, because Cannot load specified object


Traceback (most recent call last):
  File "extbench/rundacapo.py", line 66, in <module>
    main()
  File "extbench/rundacapo.py", line 48, in main
    ITERATIONS + 1), platform)
  File "/home/kruninit/warmup_experiment/krun/krun/util.py", line 107, in run_shell_cmd_bench
    fatal(msg)
  File "/home/kruninit/warmup_experiment/krun/krun/util.py", line 52, in fatal
    raise FatalKrunError(msg)
krun.util.FatalKrunError: Command failed: '$JAVA_HOME/bin/java -jar extbench/dacapo-9.12-bach.jar avrora -n 2001'
stdout:

stderr:
Error: dl failure on line 902
Error: failed /home/kruninit/warmup_experiment/work/openjdk/build/bsd-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/server/libjvm.so, because Cannot load specified object


gmake: *** [Makefile:71: bench-dacapo] Error 1
$ file /home/kruninit/warmup_experiment/work/openjdk/build/bsd-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/server/libjvm.so  
/home/kruninit/warmup_experiment/work/openjdk/build/bsd-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/server/libjvm.so: ELF 64-bit LSB shared object, x86-64, version 1
```

**Comment by ltratt** [comment]
I have no idea what that is TBH... Thoughts?

**Comment by vext01** [comment]
```
$ dmesg
...
java(55312): mprotect W^X violation
$ mount
/dev/sd0a on / type ffs (local, wxallowed)
```

This is weird because I tested all of the VMs on a machine with W^X in place. I guess I missed something.

**Comment by ltratt** [comment]
OK, so it's unconnected to this PR?

**Comment by vext01** [comment]
Yeah.

But why did the main experiment work without W^X problems?

**Comment by ltratt** [comment]
That's above my pay grade to answer ;)

Anyway, squashed and ready for merge.

**Comment by vext01** [comment]
OK, I'll look into that at some point then.

This is good to merge.

**Review by vext01 — APPROVED** [review]

**Pull request merged**
