### PR TITLE
Slightly wider histograms in tables.

### PR DESCRIPTION
**Pull request by snim2**
What it says on the tin.

### CODE REVIEW

**Review by ltratt — APPROVED** [review]

**Comment by ltratt** [comment]
Is it just me or have the bars not got wider but the gaps between bars is wider? [This may be a reasonable thing to do, but I'm not sure if it's what we intended or not.]

**Comment by snim2** [comment]
Good question, let me have a look.

**Comment by snim2** [comment]
OK, let me know if this is good to squash. I've checked through and I don't *think* any of the bars are overlapping (which was the reason behind the rather cautious value for the bar width from before).

**Comment by ltratt** [comment]
I like it -- please squash away!

**Comment by snim2** [comment]
Squashed!

**Pull request merged**
