### PR TITLE
Fix issues with changepoints

### PR DESCRIPTION
**Pull request by snim2**
/cc @rkillick

### CODE REVIEW

**Comment by snim2** [comment]
On Ubuntu, using CRAN to install `r-base` and `r-base-dev`: https://www.datascienceriot.com/how-to-install-r-in-linux-ubuntu-16-04-xenial-xerus/

**Comment by ltratt** [comment]
Obvious dumb question: why prefer deepcopy? After all, it's much more expensive! Is there a semantic reason why it's necessary?

**Comment by snim2** [comment]
This was what we were playing with at the last thrash. It doesn't seem to make any difference to the results, but you thought it might be the source of a bug. Before this branch is ready for review I'll check this again and revert if we can.

**Comment by ltratt** [comment]
The suggestion was simply because copy.copy on a list is equivalent to the more normal `[:]`, so it did seem a possible thing to look at. Looking at it again once everything's fixed sounds sensible to me.

**Comment by snim2** [comment]
Squashed and ready for review

**Review by ltratt — APPROVED** [review]

**Pull request merged**
