### PR TITLE
Look for instrumentation data in the right place.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by ltratt** [comment]
I think @vext01 should do this one (I'm clueless about this part of things). Switching assignees.

**Comment by vext01** [comment]
So where was it erroneously looking before? Just wondering why it worked when we make the plots manually...

**Comment by snim2** [comment]
I suspect because everything was in the same directory. When the data was in the `annotated_data` directory, it would look for `annotated_dataannotated_data/FILENAME`

**Comment by vext01** [comment]
OK

**Review by vext01 — APPROVED** [review]

**Pull request merged**
