### PR TITLE
C nbody

### PR DESCRIPTION
**Pull request by vext01**
Add C version of nbody and add checksum.

Renaming of `advance` is to avoid a clash with a function of the same name in glibc.

OK?

### CODE REVIEW

**Comment by ltratt** [comment]
I don't understand why `setup_state` is a separate function. It would seem to make sense _iff_ the C runner in Krun separately called "setup" vs "run iter"?

**Comment by vext01** [comment]
I don't understand what you mean.

`setup_state()`  needs to be called once  per innermost iteration, not once per krun iteration.

**Comment by ltratt** [comment]
I guess my point is: a two line function seems pointless -- it makes the code harder to read.

I'm also curious as to whether the `malloc` should be inside the `for` loop or not (I kind of think it should, but I suppose it depends on how the other language versions do this).

**Comment by vext01** [comment]
Inlining the function is trivial. The malloc can go in either position, but to put it in side the loop is wasteful (in the other benchmarks, I have tried to be as efficient as possible too).

**Comment by vext01** [comment]
OK?

**Comment by ltratt** [comment]
OK!

**Comment by ltratt** [comment]
Do you want to squash or should I merge as-is?

**Comment by vext01** [comment]
I'll splat that last commit in.

**Comment by vext01** [comment]
Squelch. Go ahead.

**Pull request merged**
