### PR TITLE
Remove filename extensions from the bin/ directory.

### PR DESCRIPTION
**Pull request by ltratt**
No-one should need to care what language things in `bin/` are written in: if the things are executable, calling `bin/X` should be sufficient.

### CODE REVIEW

**Review by vext01 — APPROVED** [review]
This is fine.

**Comment by vext01** [comment]
Merge as is?

**Comment by ltratt** [comment]
So long as you think it's correct :)

**Comment by vext01** [comment]
Oh, can you grep the tree for invocations of any of the scripts you renamed?

**Comment by ltratt** [comment]
I did that, but I wouldn't mind someone else checking :)

**Comment by vext01** [comment]
Yep, LGTM.

**Pull request merged**
