### PR TITLE
Fix --xlimits with insets.

### PR DESCRIPTION
**Pull request by vext01**
Hi Sarah, I think this is the fix we need for the insets, but please check carefully.

We should probably test this on a large run.

Sorry about the crap commit message, will fix at the end.

### CODE REVIEW

**Comment by vext01** [comment]
Example:
[new_warmup_no_migrate.pdf](https://github.com/softdevteam/warmup_experiment/files/865541/new_warmup_no_migrate.pdf)

**Comment by vext01** [comment]
Also added my debugging statements to help with testing.

**Comment by vext01** [comment]
Was going to post more examples, but hit:
https://github.com/softdevteam/warmup_experiment/issues/360

**Comment by snim2** [comment]
OK, I've looked through a full v0.7 document for bencher5 and this branch works fine there.

**Comment by vext01** [comment]
Sadly this isn't right still:

```
$ python ../warmup_experiment//bin/plot_krun_results --xlimits 30,200 --inset-xlimits 50,100 --with-changepoint-means
--no-zoom --core-cycles 3 --export-size 5,6 -o examples/new_warmup_no_migrate.pdf -b bencher5:nbody:HHVM:default-php:8
 -b bencher5:binarytrees:HHVM:default-php:8 -b bencher5:nbody:PyPy:default-python:8 -b bencher5:fasta:C:default-c:8 -b
 bencher5:richards:C:default-c:8 -b bencher5:richards:HHVM:default-php:8 -b bencher5:richards:LuaJIT:default-lua:8 -b
bencher5:spectralnorm:HHVM:default-php:1 -b bencher5:spectralnorm:PyPy:default-python:1 -b bencher5:spectralnorm:Hotsp
ot:default-java:1 warmup_results_0_8_linux2_i7_4790_outliers_w200_changepoints.json.bz2
...
Plotting Linux$_\mathrm{4790}$: Spectral Norm (HHVM) on page 07 of 09.
1 plots arranged in 1 rows and 1 columns.
Saved: examples/new_warmup_no_migrate.pdf
Traceback (most recent call last):
  File "../warmup_experiment//bin/plot_krun_results", line 1429, in <module>
    inset_xlimits=options.inset_xlimits)
  File "../warmup_experiment//bin/plot_krun_results", line 305, in main
    core_cycles, cycles_ylimits, inset_xlimits)
  File "../warmup_experiment//bin/plot_krun_results", line 850, in draw_page
    chart.plot_inset(chart.wallclock_axis, fig)
  File "../warmup_experiment//bin/plot_krun_results", line 653, in plot_inset
    inset_collides, dist = collide_rect(rect, fig, axis, self.wallclock_data, self.x_bounds)
  File "/home/edd/research/warmup_experiment/warmup/plotting.py", line 101, in collide_rect
    minimum_y = min(data[x_left:x_right])
ValueError: min() arg is an empty sequence
```

**Comment by snim2** [comment]
That traceback is from a bug that has been fixed in master now.

**Comment by snim2** [comment]
LGTM

**Comment by vext01** [comment]
Splat.

**Review by snim2 — APPROVED** [review]

**Pull request merged**
