### PR TITLE
Larger fonts

### PR DESCRIPTION
**Pull request by vext01**
Larger fonts, to make the graphs in the paper readable.

fonts

OK?

### CODE REVIEW

**Comment by snim2** [comment]
Did you test this with interactive mode and with a whole page of charts yet?

**Comment by vext01** [comment]
I tested a whole page of charts, hence the spacing adjustment. I'm not too fussed about interactive mode right now, just trying to hammer the paper draft into shape.

**Comment by snim2** [comment]
OK, testing this now...

**Comment by snim2** [comment]
OK, I guess you tested this with measurements only, which is what will go in the paper. On both my machines, if I turn on the mean and sigma plotting the text overlays the charts in all sorts of places, if I only plot data I get something like this:

larger_fonts

**Comment by vext01** [comment]
Why are the plots so narrow?

**Comment by snim2** [comment]
Which axis?

**Comment by vext01** [comment]
Y. The graph heights are surprisingly short. Not sure why...

**Comment by snim2** [comment]
I think the first iteration is covered by the axis itself?

**Comment by vext01** [comment]
OK, I just realised you are in interactive mode.

In this mode, it tries to fit all execs in the window causing overlap. The change I just pushed reverts the old font size only for interactive mode, but I still see overlap even on my large monitor and maximised window.

This is a separate bug. We have never used interactive mode with so many executions.

**Comment by snim2** [comment]
OK, testing this again.

**Comment by snim2** [comment]
OK, so the interactive mode is better, still a bit of overlap but readable. The non-interactive mode is OK, but the legend goes outside the chart, and even if you only plot data the legend text is very large. Here is an example: 
larger_fonts_legend

**Comment by vext01** [comment]
OK, I think the legend text needs to:
- Be shorter
- Be in one column

Do you mind if we fix that separately so I can push on with the draft, which will not include a legend?

**Comment by snim2** [comment]
OK, that's fine. BTW one column will mean that the legend text is always written over the data, which is why I increased the column count. So, I think we will need to play around quite a bit before we get something that we are happy with. What I would have preferred was to have just one legend, outside of all the plots, but I couldn't figure out how to do it.

Do you want to squash this PR before I merge?

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
Thanks!

**Pull request merged**
