### PR TITLE
Run the JDK first in dacapo.

### PR DESCRIPTION
**Pull request by vext01**
OK?

Do you want me to kill both runs of dacapo?

bencher5 it still happily making progress:
`-rw-r--r--  1 vext01 vext01   4528359 Mar 28 16:10 bencher5.dacapo.graal.results`

It's made it past 30 pexecs of lusearch/graal.

Tough call.

### CODE REVIEW

**Comment by snim2** [comment]
Code-wise this looks OK to me but I notice that the two scripts in `extbench` have different file permissions:

```bash
$ ls -lh
total 12K
-rw-r--r-- 1 snim2 snim2 4.2K Mar 28 17:30 rundacapo.py
-rwxr-xr-x 1 snim2 snim2 3.4K Mar 27 17:58 runoctane.py
```

**Comment by vext01** [comment]
fixed

**Comment by snim2** [comment]
OK, ready to squash?

**Comment by vext01** [comment]
Probably leave them apart, as they are separate fixes.

**Comment by snim2** [comment]
OK, so you are happy for me to merge now?

**Review by snim2 — APPROVED** [review]

**Comment by vext01** [comment]
go ahead

**Pull request merged**
