### PR TITLE
Attempt to fix v8 build.

### PR DESCRIPTION
**Pull request by ltratt**
Don't merge quite yet (a full build is underway). But if you spot anything dumb, please let me know!

### CODE REVIEW

**Comment by vext01** [comment]
Looks OK. Can we check the result of `git checkout` and `gclient sync` or do they also fail like `fetch` does?

**Comment by ltratt** [comment]
They can also fail :( Though it's not ideal, I think we're OK, because the later build can't possibly succeed if the earlier things fail -- and the later build is checked properly. So, at worst, we pick up the error a bit later than we'd like.

**Comment by vext01** [comment]
Fair enough.

**Comment by vext01** [comment]
Should we wait until we hear back from Jakob? I have a suspicion that the 4.8 branch is not stable code. But then again, nor is graal or jruby/truffle.

**Comment by ltratt** [comment]
If he comes back and tells us we should be using another tag, we can merge that later. [I'm not sure what timezone he's operating in.]

**Comment by ltratt** [comment]
It works! So it's ready for merging.

**Pull request merged**
